# Generated by Django 3.1.6 on 2021-02-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210214_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='image',
            field=models.ImageField(default='default_footer.png', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='header',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploads'),
        ),
    ]
